/**
 * Same-hash JIT linkage — the construction that needs no proof.
 *
 * The `linked` construction (see `linkageDualSha256.ts`) exists only because *one* FNN node cannot hold
 * invoice(H) and also pay invoice(H). Two distinct hashes then need a zero-knowledge proof that they share a
 * secret. Give the LSP a second node and the constraint disappears: the hold node and the paying node are
 * separate processes, so both invoices can carry the *same* hash.
 *
 *   hash     = sha256(S)   -- both the customer hold invoice and the merchant invoice
 *   preimage = S           -- 32 bytes, generated by the merchant
 *
 * The security property is unchanged, and for the same reason: **the merchant generates S**. The hold node
 * can settle only once S exists, and S exists only once the merchant claimed its invoice. Deliver-or-refund stays
 * structural. What is removed is the proof, and with it the proving key, the circuit artifacts, and the
 * trusted setup — the merchant's whole cryptographic footprint becomes one `sha256`.
 *
 * The cost moves to the LSP, which must run two nodes and position funding capital at the paying one.
 *
 * Routing constraint: the same hash is live on two payment routes at once, so any node sitting on *both* the
 * customer's route to the hold node and the paying node's route to the merchant would learn S from the second
 * and could claim on the first. Our topology makes that set empty: the merchant payment always traverses the
 * channel the LSP just funded (a single hop, no intermediaries), and the customer's payment is already held
 * before that channel exists, so the merchant cannot yet be on any route. An LSP that forwards the merchant
 * payment over pre-existing hops instead of a fresh direct channel loses this argument.
 */
import { sha256Hex } from "./linkageDualSha256.js";

export const SAME_HASH_SCHEME = "same-hash";

export interface SameHashLink {
  /** sha256(S) — carried by both the hold invoice and the merchant invoice. */
  hash: string;
  /** S (32 bytes) — the merchant's secret; settles the merchant invoice, then the hold. */
  preimage: string;
}

/** The single hash and its preimage, for a 32-byte secret (hex or bytes). */
export function sameHashLink(secret: Uint8Array | string): SameHashLink {
  const preimage = typeof secret === "string" ? normalizeHex(secret) : toHex(secret);
  if ((preimage.length - 2) / 2 !== 32) throw new Error("JIT secret must be 32 bytes");
  return { hash: sha256Hex(preimage), preimage };
}

/**
 * Settlement check for same-hash mode, given the merchant preimage revealed by the forward payment. The hold
 * and merchant payment hashes must coincide, and the preimage must hash to them.
 */
export function verifySameHashLinkage(preimageHex: string, holdHash: string, merchantPaymentHash: string): boolean {
  if (!eq(holdHash, merchantPaymentHash)) return false;
  if ((normalizeHex(preimageHex).length - 2) / 2 !== 32) return false;
  return eq(sha256Hex(preimageHex), holdHash);
}

function eq(a: string, b: string): boolean {
  return a.toLowerCase() === b.toLowerCase();
}

function normalizeHex(hex: string): string {
  const h = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (h.length % 2 !== 0 || !/^[0-9a-fA-F]*$/.test(h)) throw new Error("invalid hex");
  return "0x" + h.toLowerCase();
}

function toHex(b: Uint8Array): string {
  return "0x" + [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
}
